# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: subscriptions.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='subscriptions.proto',
  package='sr.grpc',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x13subscriptions.proto\x12\x07sr.grpc\"\x1e\n\x0eMeetingRequest\x12\x0c\n\x04team\x18\x01 \x01(\t\"\'\n\x06Person\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07surname\x18\x02 \x01(\t\"u\n\x0fMeetingResponse\x12\x0c\n\x04room\x18\x01 \x01(\t\x12\x10\n\x08\x64\x61tetime\x18\x02 \x01(\t\x12\x1b\n\x04type\x18\x03 \x01(\x0e\x32\r.sr.grpc.Type\x12%\n\x0cparticipants\x18\x04 \x03(\x0b\x32\x0f.sr.grpc.Person\"M\n\x0eWeatherRequest\x12\x0c\n\x04\x63ity\x18\x01 \x01(\t\x12\x1a\n\x12\x64\x65siredTemperature\x18\x02 \x01(\x02\x12\x11\n\ttolerance\x18\x03 \x01(\x02\"c\n\x0fWeatherResponse\x12\x12\n\nsatisfying\x18\x01 \x01(\x08\x12\x13\n\x0btemperature\x18\x02 \x01(\x02\x12\'\n\nconditions\x18\x03 \x01(\x0e\x32\x13.sr.grpc.Conditions*4\n\x04Type\x12\x0b\n\x07STANDUP\x10\x00\x12\x10\n\x0c\x43OMPANY_WIDE\x10\x01\x12\r\n\tDIRECTORS\x10\x02*:\n\nConditions\x12\t\n\x05SUNNY\x10\x00\x12\n\n\x06\x43LOUDY\x10\x01\x12\t\n\x05RAINY\x10\x02\x12\n\n\x06STORMY\x10\x03\x32\xa8\x01\n\x13SubscriptionService\x12G\n\x10subscribeWeather\x12\x17.sr.grpc.WeatherRequest\x1a\x18.sr.grpc.WeatherResponse0\x01\x12H\n\x11subscribeMeetings\x12\x17.sr.grpc.MeetingRequest\x1a\x18.sr.grpc.MeetingResponse0\x01\x62\x06proto3'
)

_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='sr.grpc.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STANDUP', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMPANY_WIDE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIRECTORS', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=404,
  serialized_end=456,
)
_sym_db.RegisterEnumDescriptor(_TYPE)

Type = enum_type_wrapper.EnumTypeWrapper(_TYPE)
_CONDITIONS = _descriptor.EnumDescriptor(
  name='Conditions',
  full_name='sr.grpc.Conditions',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUNNY', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLOUDY', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RAINY', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STORMY', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=458,
  serialized_end=516,
)
_sym_db.RegisterEnumDescriptor(_CONDITIONS)

Conditions = enum_type_wrapper.EnumTypeWrapper(_CONDITIONS)
STANDUP = 0
COMPANY_WIDE = 1
DIRECTORS = 2
SUNNY = 0
CLOUDY = 1
RAINY = 2
STORMY = 3



_MEETINGREQUEST = _descriptor.Descriptor(
  name='MeetingRequest',
  full_name='sr.grpc.MeetingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='team', full_name='sr.grpc.MeetingRequest.team', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=62,
)


_PERSON = _descriptor.Descriptor(
  name='Person',
  full_name='sr.grpc.Person',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='sr.grpc.Person.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='surname', full_name='sr.grpc.Person.surname', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=103,
)


_MEETINGRESPONSE = _descriptor.Descriptor(
  name='MeetingResponse',
  full_name='sr.grpc.MeetingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='room', full_name='sr.grpc.MeetingResponse.room', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='datetime', full_name='sr.grpc.MeetingResponse.datetime', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='sr.grpc.MeetingResponse.type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='participants', full_name='sr.grpc.MeetingResponse.participants', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=222,
)


_WEATHERREQUEST = _descriptor.Descriptor(
  name='WeatherRequest',
  full_name='sr.grpc.WeatherRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='city', full_name='sr.grpc.WeatherRequest.city', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='desiredTemperature', full_name='sr.grpc.WeatherRequest.desiredTemperature', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tolerance', full_name='sr.grpc.WeatherRequest.tolerance', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=301,
)


_WEATHERRESPONSE = _descriptor.Descriptor(
  name='WeatherResponse',
  full_name='sr.grpc.WeatherResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='satisfying', full_name='sr.grpc.WeatherResponse.satisfying', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='sr.grpc.WeatherResponse.temperature', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='conditions', full_name='sr.grpc.WeatherResponse.conditions', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=303,
  serialized_end=402,
)

_MEETINGRESPONSE.fields_by_name['type'].enum_type = _TYPE
_MEETINGRESPONSE.fields_by_name['participants'].message_type = _PERSON
_WEATHERRESPONSE.fields_by_name['conditions'].enum_type = _CONDITIONS
DESCRIPTOR.message_types_by_name['MeetingRequest'] = _MEETINGREQUEST
DESCRIPTOR.message_types_by_name['Person'] = _PERSON
DESCRIPTOR.message_types_by_name['MeetingResponse'] = _MEETINGRESPONSE
DESCRIPTOR.message_types_by_name['WeatherRequest'] = _WEATHERREQUEST
DESCRIPTOR.message_types_by_name['WeatherResponse'] = _WEATHERRESPONSE
DESCRIPTOR.enum_types_by_name['Type'] = _TYPE
DESCRIPTOR.enum_types_by_name['Conditions'] = _CONDITIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MeetingRequest = _reflection.GeneratedProtocolMessageType('MeetingRequest', (_message.Message,), {
  'DESCRIPTOR' : _MEETINGREQUEST,
  '__module__' : 'subscriptions_pb2'
  # @@protoc_insertion_point(class_scope:sr.grpc.MeetingRequest)
  })
_sym_db.RegisterMessage(MeetingRequest)

Person = _reflection.GeneratedProtocolMessageType('Person', (_message.Message,), {
  'DESCRIPTOR' : _PERSON,
  '__module__' : 'subscriptions_pb2'
  # @@protoc_insertion_point(class_scope:sr.grpc.Person)
  })
_sym_db.RegisterMessage(Person)

MeetingResponse = _reflection.GeneratedProtocolMessageType('MeetingResponse', (_message.Message,), {
  'DESCRIPTOR' : _MEETINGRESPONSE,
  '__module__' : 'subscriptions_pb2'
  # @@protoc_insertion_point(class_scope:sr.grpc.MeetingResponse)
  })
_sym_db.RegisterMessage(MeetingResponse)

WeatherRequest = _reflection.GeneratedProtocolMessageType('WeatherRequest', (_message.Message,), {
  'DESCRIPTOR' : _WEATHERREQUEST,
  '__module__' : 'subscriptions_pb2'
  # @@protoc_insertion_point(class_scope:sr.grpc.WeatherRequest)
  })
_sym_db.RegisterMessage(WeatherRequest)

WeatherResponse = _reflection.GeneratedProtocolMessageType('WeatherResponse', (_message.Message,), {
  'DESCRIPTOR' : _WEATHERRESPONSE,
  '__module__' : 'subscriptions_pb2'
  # @@protoc_insertion_point(class_scope:sr.grpc.WeatherResponse)
  })
_sym_db.RegisterMessage(WeatherResponse)



_SUBSCRIPTIONSERVICE = _descriptor.ServiceDescriptor(
  name='SubscriptionService',
  full_name='sr.grpc.SubscriptionService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=519,
  serialized_end=687,
  methods=[
  _descriptor.MethodDescriptor(
    name='subscribeWeather',
    full_name='sr.grpc.SubscriptionService.subscribeWeather',
    index=0,
    containing_service=None,
    input_type=_WEATHERREQUEST,
    output_type=_WEATHERRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='subscribeMeetings',
    full_name='sr.grpc.SubscriptionService.subscribeMeetings',
    index=1,
    containing_service=None,
    input_type=_MEETINGREQUEST,
    output_type=_MEETINGRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SUBSCRIPTIONSERVICE)

DESCRIPTOR.services_by_name['SubscriptionService'] = _SUBSCRIPTIONSERVICE

# @@protoc_insertion_point(module_scope)
